"""add user report table

Revision ID: 58b0f83cbf2b
Revises: 686821f28817
Create Date: 2025-10-02 09:45:41.632160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b0f83cbf2b'
down_revision = '686821f28817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_report_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_report_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_report_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_report_status'))

    op.drop_table('user_report')
    # ### end Alembic commands ###
