"""increase size of image_file column

Revision ID: 686821f28817
Revises: 6de9a04f7a35
Create Date: 2025-09-20 22:27:52.987386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686821f28817'
down_revision = '6de9a04f7a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'default.jpg'"))

    # ### end Alembic commands ###
